version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  python-app:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    command: python /app/scripts/load.py
