version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  python-app:
    build:
      context: .
    depends_on:
      - mongodb
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    command: python /app/scripts/main.py
    env_file: .env  # Charge les variables d'environnement à partir du fichier .env
